name: speedtransfer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg-python
  - imageio
  - ipython
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pillow
  - pytz
  - scikit-image
  - scipy
  - seaborn
  - sshtunnel
  - pip
  - pip:
      - opencv-python-headless
      - torch
      - git+https://github.com/BioroboticsLab/bb_behavior
      - git+https://github.com/BioroboticsLab/bb_circadian
      - git+https://github.com/BioroboticsLab/bb_rhythm
      - git+https://github.com/BioroboticsLab/bb_utils
      - git+https://github.com/walachey/slurmhelper